# Generated by Django 3.0.8 on 2020-08-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Long_URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddField(
            model_name='custom_extension',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Long_URL'),
        ),
    ]
