# Generated by Django 3.0.8 on 2020-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200827_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='long_url',
            name='extension',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='long_url',
            name='full_url',
            field=models.URLField(default='www.google.com', unique=True),
        ),
        migrations.DeleteModel(
            name='custom_extension',
        ),
    ]
