# Generated by Django 3.0.8 on 2020-08-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200827_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(default='', max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Long_URL')),
            ],
        ),
    ]
