# Generated by Django 3.0.8 on 2020-08-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_custom_extension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom_extension',
        ),
    ]
