# Generated by Django 3.0.8 on 2020-08-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200829_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_extension',
            name='extension',
            field=models.CharField(default='f', max_length=200),
        ),
        migrations.AlterField(
            model_name='custom_extension',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Long_URL'),
        ),
    ]
