# Generated by Django 3.0.8 on 2020-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200829_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_url',
            name='full_url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
